@extends('layouts.app')

@section('content')
    @include('sections.navbar')
    @include('partials.landing.hero')
    {{-- @include('partials.landing.stats') --}}
    @include('partials.landing.services')
    @include('partials.landing.maps-process')
    @include('partials.landing.website')
    @include('partials.landing.pos')
    @include('partials.landing.about')
    @include('partials.landing.team')
    @include('partials.landing.testimonials')
    @include('partials.landing.why-us')
    @include('partials.landing.blog-section')
    @include('partials.landing.faq')
    @include('partials.landing.contact')
    @include('partials.landing.footer')
    @include('partials.landing.quote-modal')
@endsection
