<?php

return [
    'posts' => [
        [
            'slug' => 'rank-higher-google-maps-2026',
            'title' => '7 Proven Ways to Rank Higher on Google Maps in 2026',
            'category' => 'Local SEO',
            'excerpt' => 'Google Maps rankings are more competitive than ever. Here are the 7 strategies we use to move clients into the 3-pack — and keep them there.',
            'author' => 'Hamza Sheikh',
            'author_role' => 'Head of Local SEO',
            'author_initials' => 'HS',
            'author_email' => 'hamza@mapzoon.com',
            'date' => '2026-06-18',
            'reading_time' => 6,
            'icon' => 'map-pin',
            'body' => [
                ['type' => 'paragraph', 'text' => "Ranking in the Google Maps 3-pack used to be about stuffing your business name with keywords. That stopped working years ago. Today, Google rewards businesses that look genuinely active, trusted, and relevant to the searcher's exact location — and the gap between page one and page three usually comes down to a handful of fixable details."],
                ['type' => 'heading', 'text' => '1. Treat your Google Business Profile as a living page, not a one-time form'],
                ['type' => 'paragraph', 'text' => "Most businesses fill out their profile once and never touch it again. The ones that rank post updates, add new photos, and keep their hours and services current — Google notices activity."],
                ['type' => 'list', 'items' => [
                    'Pick the most specific primary category available, not the broadest one',
                    'Add every relevant service with a short description',
                    'Upload new photos at least twice a month',
                    'Respond to every review within 48 hours',
                ]],
                ['type' => 'heading', 'text' => '2. Citation consistency still matters more than people think'],
                ['type' => 'paragraph', 'text' => "Your business Name, Address, and Phone number (NAP) need to match exactly across every directory Google can find. Even small inconsistencies — a missing suite number, an old phone number on one listing — quietly erode trust signals."],
                ['type' => 'quote', 'text' => "We audited a client's citations and found their old address listed on 11 directories, two years after they'd moved three blocks away. Fixing that alone moved them up four spots in six weeks.", 'cite' => 'Hamza Sheikh, Head of Local SEO'],
                ['type' => 'heading', 'text' => 'Ranking factors, roughly in order of impact'],
                ['type' => 'table', 'headers' => ['Factor', 'Impact', 'Effort to fix'], 'rows' => [
                    ['Proximity to searcher', 'Very High', 'Not controllable'],
                    ['Review quantity & recency', 'High', 'Medium'],
                    ['Citation consistency', 'High', 'Low'],
                    ['Profile completeness', 'Medium', 'Low'],
                    ['Website relevance', 'Medium', 'High'],
                ]],
                ['type' => 'image', 'caption' => 'A simplified view of how proximity, relevance, and prominence combine to determine Maps ranking.'],
                ['type' => 'paragraph', 'text' => "None of this happens overnight — most of our clients see meaningful movement within 4 to 8 weeks. But unlike paid ads, every one of these fixes keeps compounding long after you've made it."],
            ],
        ],
        [
            'slug' => 'google-business-profile-optimization-checklist',
            'title' => 'Google Business Profile Optimization: The Complete Checklist',
            'category' => 'Google Business Profile',
            'excerpt' => 'Most businesses only fill out half of their Google Business Profile. This checklist covers every section that actually moves the needle.',
            'author' => 'Ayesha Malik',
            'author_role' => 'Founder & CEO',
            'author_initials' => 'AM',
            'author_email' => 'ayesha@mapzoon.com',
            'date' => '2026-06-10',
            'reading_time' => 5,
            'icon' => 'profile',
            'body' => [
                ['type' => 'paragraph', 'text' => "When we run a free audit, the Google Business Profile section is almost always where we find the most low-effort, high-impact fixes. Here's the exact checklist our team runs through for every new client."],
                ['type' => 'heading', 'text' => 'The profile basics'],
                ['type' => 'list', 'items' => [
                    'Business name matches your signage exactly — no extra keywords',
                    'Primary category is the most specific match available',
                    'Secondary categories cover every real service you offer',
                    'Hours are accurate, including holiday hours',
                    'Service area is set correctly if you don\'t serve walk-ins',
                ]],
                ['type' => 'heading', 'text' => 'Trust signals'],
                ['type' => 'paragraph', 'text' => "A complete profile signals to Google that a business is legitimate and actively maintained. Photos, posts, and review responses all count toward this — and they're the easiest things to neglect once the initial setup is done."],
                ['type' => 'quote', 'text' => "A profile with 20 photos and weekly posts will consistently outrank a technically 'better' competitor who set their profile up once and forgot about it.", 'cite' => 'Ayesha Malik, Founder & CEO'],
                ['type' => 'image', 'caption' => 'A fully optimized profile section, ready for review.'],
                ['type' => 'heading', 'text' => 'Review management checklist'],
                ['type' => 'table', 'headers' => ['Action', 'Frequency'], 'rows' => [
                    ['Respond to new reviews', 'Within 48 hours'],
                    ['Request reviews from happy customers', 'Ongoing'],
                    ['Flag and report fake/spam reviews', 'As they appear'],
                    ['Review overall rating trend', 'Monthly'],
                ]],
                ['type' => 'paragraph', 'text' => "Run through this list once a quarter and you'll stay ahead of most local competitors who treat their profile as a one-time setup task."],
            ],
        ],
        [
            'slug' => 'why-local-businesses-need-pos-system',
            'title' => 'Why Local Businesses Need a POS System (Not Just a Website)',
            'category' => 'Business Tools',
            'excerpt' => 'A great website brings customers in the door. Here is why what happens after that matters just as much — and how a POS system closes the gap.',
            'author' => 'Bilal Ahmed',
            'author_role' => 'POS & Systems Specialist',
            'author_initials' => 'BA',
            'author_email' => 'bilal@mapzoon.com',
            'date' => '2026-05-28',
            'reading_time' => 5,
            'icon' => 'pos',
            'body' => [
                ['type' => 'paragraph', 'text' => "We spend most of our time talking about getting customers to find a business. But once they walk in or call, what happens next determines whether they come back — and whether the owner actually knows if the business is profitable."],
                ['type' => 'heading', 'text' => 'The gap a website alone can\'t close'],
                ['type' => 'paragraph', 'text' => "A website answers \"can I trust this business?\". It doesn't answer \"did today's sales cover today's costs?\" or \"which products are actually worth restocking?\". That's where most local businesses are still running on guesswork."],
                ['type' => 'list', 'items' => [
                    'Manual invoicing means delayed payments and lost paperwork',
                    'No real-time view of inventory leads to overstocking or running out',
                    'Without sales reports, pricing decisions are based on gut feeling',
                    'Customer history lives in someone\'s memory, not in the business',
                ]],
                ['type' => 'quote', 'text' => "The businesses that grow fastest aren't just the ones with the most customers — they're the ones who actually know their numbers.", 'cite' => 'Bilal Ahmed, POS & Systems Specialist'],
                ['type' => 'heading', 'text' => 'What a modern POS system actually replaces'],
                ['type' => 'table', 'headers' => ['Old way', 'With a POS system'], 'rows' => [
                    ['Handwritten or app-based invoices', 'One-tap invoices, shareable via WhatsApp'],
                    ['End-of-day manual cash counting', 'Automatic daily sales reports'],
                    ['Guessing what to restock', 'Real-time inventory alerts'],
                    ['Sticky notes for regular customers', 'Searchable customer history'],
                ]],
                ['type' => 'image', 'caption' => 'A simplified daily workflow once sales, invoicing, and inventory live in one dashboard.'],
                ['type' => 'paragraph', 'text' => "None of this requires an enterprise budget. It requires the right tool, set up correctly — which is exactly why we built ours to work alongside the marketing side, not as a separate product from a separate vendor."],
            ],
        ],
    ],
];
